### ISSUE TITLE
LateInitializationError when using adaptiveBoundaries

### ISSUE THREAD

**Issue by neylsongularte** [fleaflet/flutter_map#1049]
```
The following LateError was thrown building LayoutBuilder:
LateInitializationError: Field '_state@247051772' has not been initialized.

When the exception was thrown, this was the stack: 
#0      MapControllerImpl._state (package:flutter_map/src/map/map.dart)
#1      MapControllerImpl.zoom (package:flutter_map/src/map/map.dart:70:22)
#2      MapOptions._getControllerZoom (package:flutter_map/flutter_map.dart:371:46)
#3      MapOptions._safeArea (package:flutter_map/flutter_map.dart:339:28)
#4      MapOptions.isOutOfBounds (package:flutter_map/flutter_map.dart:310:15)
#5      MapState.move (package:flutter_map/src/map/map.dart:304:17)
#6      MapState._init (package:flutter_map/src/map/map.dart:179:7)
#7      MapState._updateSizeByOriginalSizeAndRotation (package:flutter_map/src/map/map.dart:162:7)
```

```dart
import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong2/latlong.dart';

import '../widgets/drawer.dart';

class SlidingMapPage extends StatefulWidget {
  static const String route = '/sliding_map';

  @override
  State<SlidingMapPage> createState() => _SlidingMapPageState();
}

class _SlidingMapPageState extends State<SlidingMapPage> {
  final MapController mapController = MapController();

  var latLngBonds =
  LatLngBounds(LatLng(56.6877, 11.5089), LatLng(56.7378, 11.6644));

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(title: Text('Sliding Map')),
      drawer: buildDrawer(context, SlidingMapPage.route),
      body: Padding(
        padding: EdgeInsets.all(8.0),
        child: Column(
          children: [
            Padding(
              padding: EdgeInsets.only(top: 8.0, bottom: 8.0),
              child: Text(
                  'This is a map that can be panned smoothly when the boundaries are reached.'),
            ),
            Flexible(
              child: FlutterMap(
                options: MapOptions(
                  controller: mapController,
                  center: LatLng(56.704173, 11.543808),
                  minZoom: 12.0,
                  maxZoom: 14.0,
                  zoom: 13.0,
                  swPanBoundary: LatLng(56.6877, 11.5089),
                  nePanBoundary: LatLng(56.7378, 11.6644),
                  slideOnBoundaries: true,
                  adaptiveBoundaries: true,
                  screenSize: MediaQuery.of(context).size,
                ),
                layers: [
                  TileLayerOptions(
                    tileProvider: AssetTileProvider(),
                    maxZoom: 14.0,
                    urlTemplate: 'assets/map/anholt_osmbright/{z}/{x}/{y}.png',
                  ),
                  PolygonLayerOptions(
                    polygons: [
                      Polygon(
                        color: Colors.black26,
                        points: [
                          latLngBonds.southEast,
                          latLngBonds.northEast!,
                          latLngBonds.northWest,
                          latLngBonds.southWest!
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by ibrierley** [comment]
Oh, you also want controller: mapController to be a parameter to FlutterMap and not to MapOptions.

**Comment by neylsongularte** [comment]
I want behavior similar to this:

https://openlayers.org/en/latest/examples/extent-constrained.html

**Comment by ibrierley** [comment]
Have you tried adding a "bounds" option to MapOptions. And also remove mapController from MapOptions and see how you go.

Eg
```
MapOptions(
  bounds: LatLngBounds(LatLng(58.8, 6.1), LatLng(59, 6.2)),
  boundsOptions: FitBoundsOptions(padding: EdgeInsets.all(8.0)),
),
```

**Comment by neylsongularte** [comment]
I can't use adaptiveBoundaries anyway.

**Comment by neylsongularte** [comment]
I'm using CrsSimple e Tiled Layer
