### ISSUE TITLE
[BUG] Crash when zooming/moving very fast

### ISSUE THREAD

**Issue by juliaen-dr** [fleaflet/flutter_map#1655]
### What is the bug?

Hello everybody,
unfortunately I've got to deal with a very nasty error.  

When zooming/moving around, I sometimes get the following error:

```dart
[sentry] [debug] Capture from onError 'package:latlong2/latlong/LatLng.dart': Failed assertion: line 33 pos 16: 'latitude >= -90 && latitude <= 90': is not true.
[sentry.flutterError] [error] Exception caught by gesture
                      'package:latlong2/latlong/LatLng.dart': Failed assertion: line 33 pos 16: 'latitude >= -90 && latitude <= 90': is not true.
                      #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
                      #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
                      #2      new LatLng (package:latlong2/latlong/LatLng.dart:33:16)
                      #3      SphericalMercator.unproject (package:flutter_map/src/geo/crs.dart:398:12)
                      #4      Crs.pointToLatLng (package:flutter_map/src/geo/crs.dart:37:8)
                      #5      FlutterMapState.unproject (package:flutter_map/src/map/state.dart:555:24)
                      #6      MapGestureMixin._offsetToCrs (package:flutter_map/src/gestures/gestures.dart:655:21)
                      #7      MapGestureMixin.handleScaleUpdate (package:flutter_map/src/gestures/gestures.dart:440:41)
                      #8      ScaleGestureRecognizer._advanceStateMachine.<anonymous closure> (package:flutter/src/gestures/scale.dart:702:20)
                      #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:275:24)
                      #10     ScaleGestureRecognizer._advanceStateMachine (package:flutter/src/gestures/scale.dart:701:9)
                      #11     ScaleGestureRecognizer.handleEvent (package:flutter/src/gestures/scale.dart:553:7)
                      #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
                      #13     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
                      #14     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
                      #15     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
                      #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
                      #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:488:19)
                      #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:468:22)
                      #19     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:333:11)
                      #20     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:413:7)
                      #21     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:376:5)
                      #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:323:7)
                      #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:292:9)
                      #24     _rootRunUnary (dart:async/zone.dart:1415:13)
                      #25     _CustomZone.runUnary (dart:async/zone.dart:1308:19)
                      #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217:7)
```

When this error occurs, it is always several times at once. Sometimes it also causes the App to crash with `E/DartVM  ( 9521): Exhausted heap space, trying to allocate 1915592 bytes.`.

Additional Information:
- I'm using a custom tile server

### How can we reproduce it?

It's not quite easy to reproduce, but it happens when you zoom in and out very quickly several times in a row. When the error occurs, it usually takes a long time until the tiles are loaded or they are not loaded at all.

### Platforms

Android

### Severity

Fatal: Causes the application to crash

**Comment by JaffaKetchup** [comment]
Hey @juliaen-dr,
Thanks for reporting. Can you confirm which version you're running? If you're not on the latest v6 prerelease, please try it to check whether this has already been fixed.

**Comment by juliaen-dr** [comment]
We are currently using v5.0.0. I'll try to update to v6 and keep you updated

**Comment by juliaen-dr** [comment]
@JaffaKetchup seems like it's fixed in v6. At least I can't reproduce it in v6.
