### ISSUE TITLE
MBTilesImageProvider.fromFile() is not working

### ISSUE THREAD

**Issue by aliyazdi75** [fleaflet/flutter_map#443]
I've downloaded `mbtile` file from https://openmaptiles.com/downloads/planet/ and put it on phone storage and called `MBTilesImageProvider.fromFile(mbtileFile)` and I've got these errors:
(The mbtile file was Germany like your example)
```
════════ Exception caught by image resource service ════════════════════════════════════════════════
The following message was thrown resolving an image codec:
Failed to load tile for coords: Coords(5265, 3221, 13)

Image provider: MBTileImage()
Image key: MBTileImage()
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by image resource service ════════════════════════════════════════════
Failed to load tile for coords: Coords(5266, 3221, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by image resource service ════════════════════════════════════════════
Failed to load tile for coords: Coords(5267, 3221, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by image resource service ════════════════════════════════════════════
Failed to load tile for coords: Coords(5265, 3222, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (5) Exception caught by image resource service ════════════════════════════════════════════
Failed to load tile for coords: Coords(5266, 3222, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (6) Exception caught by image resource service ════════════════════════════════════════════
Failed to load tile for coords: Coords(5267, 3222, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (7) Exception caught by image resource service ════════════════════════════════════════════
Failed to load tile for coords: Coords(5265, 3223, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (8) Exception caught by image resource service ════════════════════════════════════════════
Failed to load tile for coords: Coords(5266, 3223, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (9) Exception caught by image resource service ════════════════════════════════════════════
Failed to load tile for coords: Coords(5267, 3223, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (10) Exception caught by image resource service ═══════════════════════════════════════════
Failed to load tile for coords: Coords(5265, 3224, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (11) Exception caught by image resource service ═══════════════════════════════════════════
Failed to load tile for coords: Coords(5266, 3224, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (12) Exception caught by image resource service ═══════════════════════════════════════════
Failed to load tile for coords: Coords(5267, 3224, 13)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (13) Exception caught by image resource service ═══════════════════════════════════════════
Failed to load tile for coords: Coords(35207, 21491, 16)
════════════════════════════════════════════════════════════════════════════════════════════════════
....
```

**Comment by aliyazdi75** [comment]
Yes, these are Berlin coordinates

**Comment by aliyazdi75** [comment]
For clearcy I've changed this [File](https://github.com/johnpryan/flutter_map/blob/master/example/lib/pages/offline_mbtiles_map.dart) to this:
```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';

import '../widgets/drawer.dart';

class OfflineMBTilesMapPage extends StatefulWidget {
  static const String route = '/offline_mbtiles_map';

  const OfflineMBTilesMapPage({
    Key key,
  }) : super(key: key);

  @override
  OfflineMBTilesMapPageState createState() => OfflineMBTilesMapPageState();
}

class OfflineMBTilesMapPageState extends State<OfflineMBTilesMapPage> {
  bool load = true;
  File f;

  @override
  void initState() {
    super.initState();
    loadFile().then((onValue) {
      setState(() {
        load = onValue;
      });
    });
  }

  Future<bool> loadFile() async {
    f = File('/sdcard/Download/berlin.mbtiles');
    if (await f.exists()) {
      return false;
    }
    return true;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Offline Map (using MBTiles)')),
      drawer: buildDrawer(context, OfflineMBTilesMapPage.route),
      body: Padding(
        padding: EdgeInsets.all(8.0),
        child: Column(
          children: [
            Padding(
              padding: EdgeInsets.only(top: 8.0, bottom: 8.0),
              child: Text(
                  'This is an offline map of Berlin, Germany using a single MBTiles file. The file was built from the Stamen toner map data (http://maps.stamen.com).\n\n'
                  '(Map tiles by Stamen Design, under CC BY 3.0. Data by OpenStreetMap, under ODbL.)'),
            ),
            Flexible(
              child: load
                  ? Container()
                  : FlutterMap(
                      options: MapOptions(
                        center: LatLng(
                          52.516144,
                          13.404938,
                        ),
                        minZoom: 12.0,
                        maxZoom: 14.0,
                        zoom: 12.0,
                        swPanBoundary: LatLng(52.492205, 13.282081),
                        nePanBoundary: LatLng(52.540084, 13.527795),
                      ),
                      layers: [
                        TileLayerOptions(
                            tileProvider: MBTilesImageProvider.fromFile(f),
                            maxZoom: 14.0,
                            backgroundColor: Colors.white,
                            tms: true),
                      ],
                    ),
            ),
          ],
        ),
      ),
    );
  }
}
```
and copy `berlin.mbtile` from `assets` to `/sdcard/Download/berlin.mbtiles` on my emulator.
And I've got this log:
```D/EGL_emulation(22914): eglMakeCurrent: 0xe3a882a0: ver 2 0 (tinfo 0xc1efd4e0)
D/eglCodecCommon(22914): setVertexArrayObject: set vao to 0 (0) 1 0
I/Choreographer(22914): Skipped 30 frames!  The application may be doing too much work on its main thread.
Syncing files to device Android SDK built for x86...
D/eglCodecCommon(22914): setVertexArrayObject: set vao to 0 (0) 1 0
D/EGL_emulation(22914): eglMakeCurrent: 0xe3a89860: ver 2 0 (tinfo 0xe3a792d0)
D/eglCodecCommon(22914): setVertexArrayObject: set vao to 0 (0) 7 0
E/SQLiteLog(22914): (14) cannot open file at line 36683 of [c255889bd9]
E/SQLiteLog(22914): (14) os_unix.c:36683: (13) open(/sdcard/Download/berlin.mbtiles) - 
E/SQLiteDatabase(22914): Failed to open database '/sdcard/Download/berlin.mbtiles'.
E/SQLiteDatabase(22914): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:215)
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:197)
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:915)
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:895)
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:786)
E/SQLiteDatabase(22914): 	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:733)
E/SQLiteDatabase(22914): 	at com.tekartik.sqflite.Database.open(Database.java:26)
E/SQLiteDatabase(22914): 	at com.tekartik.sqflite.SqflitePlugin$6.run(SqflitePlugin.java:772)
E/SQLiteDatabase(22914): 	at android.os.Handler.handleCallback(Handler.java:883)
E/SQLiteDatabase(22914): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/SQLiteDatabase(22914): 	at android.os.Looper.loop(Looper.java:214)
E/SQLiteDatabase(22914): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/flutter (22914): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DatabaseException(open_failed /sdcard/Download/berlin.mbtiles)
E/flutter (22914): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:12:7)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25:7)
E/flutter (22914): #2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:188:15)
E/flutter (22914): #3      SqfliteDatabaseMixin.openDatabase (package:sqflite/src/database_mixin.dart:527:15)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #4      SqfliteDatabaseMixin.doOpen (package:sqflite/src/database_mixin.dart:620:28)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #5      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:46:22)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #6      SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite/src/factory_mixin.dart:104:43)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #7      ReentrantLock.synchronized.<anonymous closure>.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:33:24)
E/flutter (22914): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (22914): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (22914): #10     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (22914): #11     runZoned (dart:async/zone.dart:1463:12)
E/flutter (22914): #12     ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:32:24)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #13     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #14     ReentrantLock.synchronized (package:synchronized/src/reentrant_lock.dart:28:17)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #15     SqfliteDatabaseFactoryMixin.openDatabase (package:sqflite/src/factory_mixin.dart:70:17)
E/flutter (22914): #16     openDatabase (package:sqflite/sqflite.dart:153:26)
E/flutter (22914): #17     MBTilesImageProvider._loadMBTilesDatabase (package:flutter_map/src/layer/tile_provider/mbtiles_image_provider.dart:35:25)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #18     new MBTilesImageProvider._ (package:flutter_map/src/layer/tile_provider/mbtiles_image_provider.dart:22:16)
E/flutter (22914): #19     new MBTilesImageProvider.fromFile (package:flutter_map/src/layer/tile_provider/mbtiles_image_provider.dart:29:28)
E/flutter (22914): #20     OfflineMBTilesMapPageState.build (package:flutter_map_example/pages/offline_mbtiles_map.dart:74:64)
E/flutter (22914): #21     StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
E/flutter (22914): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
E/flutter (22914): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (22914): #24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
E/flutter (22914): #25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
E/flutter (22914): #26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
E/flutter (22914): #27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
E/flutter (22914): #28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
E/flutter (22914): #29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
E/flutter (22914): #30     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (22914): #31     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (22914): #32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (22914): #33     _invoke (dart:ui/hooks.dart:249:10)
E/flutter (22914): #34     _drawFrame (dart:ui/hooks.dart:207:3)
E/flutter (22914): 
I/chatty  (22914): uid=10137(com.johnpryan.leafletflutterexample) Thread-2 identical 7 lines
E/flutter (22914): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DatabaseException(open_failed /sdcard/Download/berlin.mbtiles)
E/flutter (22914): #0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:12:7)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #1      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:25:7)
E/flutter (22914): #2      SqfliteDatabaseMixin.safeInvokeMethod (package:sqflite/src/database_mixin.dart:188:15)
E/flutter (22914): #3      SqfliteDatabaseMixin.openDatabase (package:sqflite/src/database_mixin.dart:527:15)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #4      SqfliteDatabaseMixin.doOpen (package:sqflite/src/database_mixin.dart:620:28)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #5      SqfliteDatabaseOpenHelper.openDatabase (package:sqflite/src/database.dart:46:22)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #6      SqfliteDatabaseFactoryMixin.openDatabase.<anonymous closure> (package:sqflite/src/factory_mixin.dart:104:43)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #7      ReentrantLock.synchronized.<anonymous closure>.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:33:24)
E/flutter (22914): #8      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (22914): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (22914): #10     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (22914): #11     runZoned (dart:async/zone.dart:1463:12)
E/flutter (22914): #12     ReentrantLock.synchronized.<anonymous closure> (package:synchronized/src/reentrant_lock.dart:32:24)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #13     BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #14     ReentrantLock.synchronized (package:synchronized/src/reentrant_lock.dart:28:17)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #15     SqfliteDatabaseFactoryMixin.openDatabase (package:sqflite/src/factory_mixin.dart:70:17)
E/flutter (22914): #16     openDatabase (package:sqflite/sqflite.dart:153:26)
E/flutter (22914): #17     MBTilesImageProvider._loadMBTilesDatabase (package:flutter_map/src/layer/tile_provider/mbtiles_image_provider.dart:35:25)
E/flutter (22914): <asynchronous suspension>
E/flutter (22914): #18     new MBTilesImageProvider._ (package:flutter_map/src/layer/tile_provider/mbtiles_image_provider.dart:22:16)
E/flutter (22914): #19     new MBTilesImageProvider.fromFile (package:flutter_map/src/layer/tile_provider/mbtiles_image_provider.dart:29:28)
E/flutter (22914): #20     OfflineMBTilesMapPageState.build (package:flutter_map_example/pages/offline_mbtiles_map.dart:74:64)
E/flutter (22914): #21     StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
E/flutter (22914): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
E/flutter (22914): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
E/flutter (22914): #24     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
E/flutter (22914): #25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
E/flutter (22914): #26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
E/flutter (22914): #27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
E/flutter (22914): #28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
E/flutter (22914): #29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
E/flutter (22914): #30     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (22914): #31     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (22914): #32     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (22914): #33     _invoke (dart:ui/hooks.dart:249:10)
E/flutter (22914): #34     _drawFrame (dart:ui/hooks.dart:207:3)
E/flutter (22914): 
```

**Comment by augusto3691** [comment]
That's beacuse the mbtiles from openmaptiles is a pbf vector format, and this flutter_maps expected a PNGs inside

**Comment by KamilSvoboda** [comment]
Same issue with raster mbtiles created here: https://export.hotosm.org/

**Comment by 4F2E4A2E** [comment]
@augusto3691 do you have any idea how we could add support for pdbf vector format?

**Comment by augusto3691** [comment]
Hello @4F2E4A2E, i give up for using this, the implementation is not straight forward and i prefer go to solutions more robust like ESRI

**Comment by 4F2E4A2E** [comment]
Okay, thanks, but what do you mean exactly? Maybe something like this? https://pub.dev/packages/flutter_map_arcgis

**Comment by ibrierley** [comment]
I did do some work on the pbf and vector tile format eg at https://github.com/ibrierley/flutter_map_vector_tiles (this was tested using mapbox vector tiles, but the pbf modules should work to decode pbf files).

Main issue I stumbled into with vector tiles was that they are very slow in canvas when pinch/zooming. So to get it fluid, you either have to convert to an image, but then you lose a bit of the essence of vector tiles. That may be ok for some people.

**Comment by djsliders** [comment]
> That's beacuse the mbtiles from openmaptiles is a pbf vector format, and this flutter_maps expected a PNGs inside

Hi,
Is there a way to convert it? I tried several tools (mb-util, mapbox tools, etc...), nothing works when given to Flutter Map.
From my side, I create a mbtiles with tilelive-copy, but it seems it is not using PNG neither.
Can you help on How to generate a correct mbtiles with the existing tools or how to convert it?
Thank you in advance for your help,
Mike

**Comment by ibrierley** [comment]
Do you have a URL to some example mbtiles and documentation about them ?

**Comment by djsliders** [comment]
I m using https://github.com/mapbox/tilelive 
with the tms module to get http tiles.
It creates a mbtiles but not compatible with MBTilesImageProvider.

**Comment by 4F2E4A2E** [comment]
We could create png based mbtiles - which are no more then sqllite db files - and tiles with http://maperitive.net/

**Comment by djsliders** [comment]
Sorry, It was my mistake. The mbtiles that I was creating wasn't containing correct information.
Thank you for the replies and thank you for this great feature ! :)

**Comment by 4F2E4A2E** [comment]
MbtilesProvider is not working on web though.
