### ISSUE TITLE
"The method 'call' was called on null" when top-left corner of the map is on screen

### ISSUE THREAD

**Issue by AmazingBite** [fleaflet/flutter_map#497]
Hi,

When the top left corner of my map is on my screen, I got this error :

```bash
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building StreamBuilder<int>(dirty, state:
_StreamBuilderBaseState<int, AsyncSnapshot<int>>#e341d):
The method 'call' was called on null.
Receiver: null
Tried calling: call(Instance of 'StatefulElement')

The relevant error-causing widget was:
  StreamBuilder<int>
  file:///Users/theo/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.8.2/lib/src/layer/marker_layer.dart:110:12

When the exception was thrown, this was the stack:
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      MarkerLayer.build.<anonymous closure> (package:flutter_map/src/layer/marker_layer.dart:134:32)
#2      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
#3      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
#9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#16     _invoke (dart:ui/hooks.dart:259:10)
#17     _drawFrame (dart:ui/hooks.dart:217:3)
(elided 3 frames from package dart:async)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

And this is my code:

```dart
FlutterMap(
   mapController: widget.mapController,
   options: new MapOptions(
      center: new LatLng(0, 0),
      zoom: 2,
      minZoom: 1,
      maxZoom: 18,
   ),
   layers: [
      TileLayerOptions(
         urlTemplate: _urlTemplate,
         subdomains: ["mt0", "mt1", "mt3"],
      ),
      PolylineLayerOptions(
         polylines: [
            Polyline(
               points: widget.polyline ?? [],
               strokeWidth: 2.0,
               color: Colors.redAccent,
            ),
         ],
      ),
      MarkerLayerOptions(markers: widget.markers ?? []),
      MarkerClusterLayerOptions(
         maxClusterRadius: 60,
         animationsOptions: AnimationsOptions(
            zoom: const Duration(seconds: 5),
            fitBound: const Duration(seconds: 5),
            centerMarker: const Duration(seconds: 5),
            fitBoundCurves: Curves.linear,
            centerMarkerCurves: Curves.linear,
         ),
         fitBoundsOptions: FitBoundsOptions(
            padding: EdgeInsets.all(20),
         ),
         markers: widget.markers ?? [],
         showPolygon: false,
         builder: (context, markers) {
            return new FloatingActionButton(
               heroTag: Random.secure(),
               child: Text(markers.length.toString()),
               onPressed: null,
            );
         },
      ),
   ],
),
```

**Comment by markqq** [comment]
Had the same problem, solved by adding `builder` to markers.

**Comment by klaszlo8207** [comment]
> 
> 
> Had the same problem, solved by adding `builder` to markers.

how?
