### ISSUE TITLE
The getter 'center' was called on null, Tried calling zoom

### ISSUE THREAD

**Issue by vaishnavmhetre** [fleaflet/flutter_map#626]
Similar to #346 although, this issue happens randomly and not specific to any component as I this is happening on default scaffold provided in example too. 

```
/// Debug Stacktrace

════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while handling a gesture:
The getter 'center' was called on null.
Receiver: null
Tried calling: center

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      MapControllerImpl.center (package:flutter_map/src/map/map.dart:44:31)
#2      _MapsPluginLayerState.animatedMapMove (package:user_location/src/user_location_layer.dart:293:31)
#3      _MapsPluginLayerState._moveMapToCurrentLocation (package:user_location/src/user_location_layer.dart:196:7)
#4      _MapsPluginLayerState.build.<anonymous closure> (package:user_location/src/user_location_layer.dart:266:19)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#90f81
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(572.2, 1027.8)
  finalLocalPosition: Offset(52.2, 41.1)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (32318): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'zoom' was called on null.
E/flutter (32318): Receiver: null
E/flutter (32318): Tried calling: zoom
E/flutter (32318): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (32318): #1      MapControllerImpl.zoom (package:flutter_map/src/map/map.dart:50:29)
E/flutter (32318): #2      _MapsPluginLayerState.forceMapUpdate (package:user_location/src/user_location_layer.dart:334:45)
E/flutter (32318): #3      _MapsPluginLayerState._subscribeToLocationChanges.<anonymous closure>.<anonymous closure> (package:user_location/src/user_location_layer.dart:179:13)
E/flutter (32318): #4      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
E/flutter (32318): #5      _MapsPluginLayerState._subscribeToLocationChanges.<anonymous closure> (package:user_location/src/user_location_layer.dart:95:9)
E/flutter (32318): #6      _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (32318): #7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (32318): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (32318): #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (32318): #10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
E/flutter (32318): #11     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)
E/flutter (32318): #12     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)
E/flutter (32318): #13     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)
E/flutter (32318): #14     _rootRunUnary (dart:async/zone.dart:1192:38)
E/flutter (32318): #15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (32318): #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (32318): #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (32318): #18     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
E/flutter (32318): #19     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
E/flutter (32318): #20     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
E/flutter (32318): #21     _rootRun (dart:async/zone.dart:1180:38)
E/flutter (32318): #22     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (32318): #23     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (32318): #24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (32318): #25     _rootRun (dart:async/zone.dart:1184:13)
E/flutter (32318): #26     _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (32318): #27     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter (32318): #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter (32318): #29     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (32318): #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
E/flutter (32318): 
```

**Comment by ibrierley** [comment]
Sounds a bit like the mapcontroller hasn't been initialised at that point maybe, so I would check through that possibility first.

**Comment by vaishnavmhetre** [comment]
Following code is used at the moment which is causing issues.

```
class DummyHolder extends StatelessWidget {
  MapController mapController = MapController();
  UserLocationOptions userLocationOptions;

  List<Marker> markers = [
    Marker(
      width: 24.0,
      height: 24.0,
      point: LatLng(51.5, -0.09),
      builder: (ctx) => Container(
        child: FlutterLogo(),
      ),
    ),
  ];

  @override
  Widget build(BuildContext context) {
    userLocationOptions = UserLocationOptions(
      context: context,
      mapController: mapController,
      markers: markers,
      showMoveToCurrentLocationFloatingActionButton: true,
    );
    return FlutterMap(
      options: MapOptions(
        center: LatLng(51.5, -0.09),
        zoom: 13.0,
        plugins: [
          UserLocationPlugin(),
        ],
      ),
      layers: [
        TileLayerOptions(
          urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
          subdomains: ['a', 'b', 'c'],
        ),
        MarkerLayerOptions(markers: markers),
        userLocationOptions,
      ],
      mapController: mapController,
    );
  }
}
```

**Comment by ibrierley** [comment]
Hmm I'd be tempted to move your class to a StatefulWidget and put your MapController() in an initState.

**Comment by vaishnavmhetre** [comment]
Let me tell you that this error happens when I click UserLocation Button in the bottom, provided by user_location, not generally! Does that affect the way we need to resolve the issue,
 as this issue doesn't happen at startup but randomly any time!

**Comment by ibrierley** [comment]
It's harder to tell without seeing all of the code, but I would still try with a stateful widget anyway.

**Comment by vaishnavmhetre** [comment]
The code I provided is the complete code all along (right from the sample provided just with UserLocationPlugin added)

**Comment by ibrierley** [comment]
I can't see what loads in DummyHolder anywhere.

Whatever, the question is, is the statelesswidget reinitialising the mapcontroller for whatever reason...is it calling for a new() DummyHolder each time.

My guess, is that it is, and reinitialising the mapcontroller....question is have you tried with a stateful widget instead, and initialising the map controller in the initState method.

**Comment by HugoHeneault** [comment]
I am having this issue too. My MapController is created in a `viewmodel` from https://pub.dev/packages/stacked so I can't move it to a `stateful` widget. I don't understand what's happening here? 🤔

**Comment by ibrierley** [comment]
Need to see some code really, but it's likely that the mapcontroller isn't initialised in time, either the first time, or when it's rebuilt or something. So typically you need to separate that assignment, so it gets initialised once and not tried to be used until that init is complete.

**Comment by sebh0602** [comment]
I have the same problem as @vaishnavmhetre and get the same error message. I followed @ibrierley 's advice and put the map in a StatefulWidget. Any help would be much appreciated.


```
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';
import 'package:proj4dart/proj4dart.dart' as proj4;

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp>{
  MapController? mapController;
  Proj4Crs? bevCRS;

  @override
  initState(){
    super.initState();
    mapController = MapController();
    this.bevCRS = Proj4Crs.fromFactory(...); //arguments removed for brevity
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Listener(
            onPointerSignal: (pointerSignal) {
              if (pointerSignal is PointerScrollEvent){
                //print(mapController?.bounds);         // - this throws an error
                //print(mapController?.center);         // - also throws an error
                if (mapController != null){
                  if (mapController!.ready){            //always false
                    print(mapController?.bounds);
                    print(mapController?.center);
                  } else{
                    print('waiting for readyness');
                    mapController?.onReady.then((val){
                      print('ready!');                  //never happens
                      print(mapController?.bounds);
                      print(mapController?.center);
                    });
                  }
                }
              }
            },
            child:FlutterMap(
              options: MapOptions(
                crs: bevCRS,
                controller: mapController,
                bounds: LatLngBounds(
                  LatLng(46,9.5),
                  LatLng(49.5,17.5)
                ),
              ),
              layers: [
                TileLayerOptions(
                  tileProvider: AssetTileProvider(),
                  urlTemplate: "map_data/{z}/{x}-{y}.png",
                  tileSize: 1024,
                  minNativeZoom: 12,
                  maxNativeZoom: 13
                ),
              ],
            )
          )
        ),
      ),
    );
  }
}
```

**Comment by ibrierley** [comment]
I suspect you need to add a mapController != null check to pointerSignal is PointerScrollEvent

**Comment by ibrierley** [comment]
Can you paste the whole code  of the widget including the mapController assignment etc, and just confirm the exact error again.

**Comment by sebh0602** [comment]
```
import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter_map/flutter_map.dart';
import 'package:latlong/latlong.dart';
import 'package:proj4dart/proj4dart.dart' as proj4;

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp>{
  MapController? mapController;
  Proj4Crs? bevCRS;

  @override
  initState(){
    super.initState();
    mapController = MapController();
    this.bevCRS = Proj4Crs.fromFactory(
      code: 'EPSG:3416',
      proj4Projection: 
        proj4.Projection.add(...);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Listener(
            onPointerSignal: (pointerSignal) async {
              if (mapController != null && pointerSignal is PointerScrollEvent){
                print(mapController?.bounds);         // - this throws an error
                //print(mapController?.center);         // - also throws an error
                if (mapController!.ready){              //always false
                  print(mapController?.bounds);
                  print(mapController?.center);
                } else{
                  print('waiting for readyness');
                  mapController?.onReady.then((val){
                    print('ready!');                    //never happens
                    print(mapController?.bounds);
                    print(mapController?.center);
                  });
                }
              }
            },
            child:FlutterMap(
              options: MapOptions(
                crs: bevCRS,
                controller: mapController,
                bounds: LatLngBounds(
                  LatLng(46,9.5),
                  LatLng(49.5,17.5)
                ),
              ),
              layers: [
                TileLayerOptions(
                  tileProvider: AssetTileProvider(),
                  urlTemplate: "map_data/{z}/{x}-{y}.png",
                  tileSize: 1024,
                  minNativeZoom: 12,
                  maxNativeZoom: 13
                ),
              ],
            )
          )
        ),
      ),
    );
  }
}

```

The error says...
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: NoSuchMethodError: The getter 'bounds' was called on null.
Receiver: null
Tried calling: bounds
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      MapControllerImpl.bounds
package:flutter_map/…/map/map.dart:61
#2      _MyAppState.build.<anonymous closure>
package:bev_map/main.dart:75
#3      _MyAppState.build.<anonymous closure>
package:bev_map/main.dart:73
#4      RenderPointerListener.handleEvent
package:flutter/…/rendering/proxy_box.dart:2839
#5      GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:419
#6      RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:287
```

**Comment by ibrierley** [comment]
What happens if you give flutter_map a center and zoom ?

**Comment by sebh0602** [comment]
I have managed to solve the issue!
The problem was the place I linked the mapController to the map.
```
child:FlutterMap(
	mapController: mapController,    //IT WORKS FINE HERE
	options: MapOptions(
		crs: bevCRS,
		//controller: mapController, //THIS DIDN'T WORK
		bounds: LatLngBounds(
			LatLng(46,9.5),
			LatLng(49.5,17.5)
		),
	),
	layers: [
		TileLayerOptions(
			tileProvider: AssetTileProvider(),
			urlTemplate: "map_data/{z}/{x}-{y}.png",
			tileSize: 1024,
			minNativeZoom: 12,
			maxNativeZoom: 13
		),
	],
)
```
Giving flutter_map a center and zoom didn't work by the way.
Thank you @ibrierley for your assistance!

**Comment by ibrierley** [comment]
Hah yes, good spot! I had missed that, well done for sorting.
