### ISSUE TITLE
[Bugs] setState after dispose

### ISSUE THREAD

**Issue by mattia-lau** [fleaflet/flutter_map#627]
```dart
E/flutter ( 6823): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: setState() called after dispose(): _MapsPluginLayerState#597c3(lifecycle state: defunct, not mounted, tickers: tracking 0 tickers)
E/flutter ( 6823): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
E/flutter ( 6823): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
E/flutter ( 6823): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
E/flutter ( 6823): #0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1197
E/flutter ( 6823): #1      State.setState 
package:flutter/…/widgets/framework.dart:1232
E/flutter ( 6823): #2      _MapsPluginLayerState._subscribeToLocationChanges.<anonymous closure> 
package:user_location/src/user_location_layer.dart:97
E/flutter ( 6823): #3      _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter ( 6823): #4      _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter ( 6823): #5      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter ( 6823): #6      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
E/flutter ( 6823): #7      _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:266:7)
E/flutter ( 6823): #8      _ForwardingStreamSubscription._add  (dart:async/stream_pipe.dart:134:11)
E/flutter ( 6823): #9      _MapStream._handleData  (dart:async/stream_pipe.dart:234:10)
E/flutter ( 6823): #10     _ForwardingStreamSubscription._handleData  (dart:async/stream_pipe.dart:166:13)
E/flutter ( 6823): #11     _rootRunUnary  (dart:async/zone.dart:1192:38)
E/flutter ( 6823): #12     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter ( 6823): #13     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter ( 6823): #14     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
E/flutter ( 6823): #15     _DelayedData.perform  (dart:async/stream_impl.dart:594:14)
E/flutter ( 6823): #16     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:710:11)
E/flutter ( 6823): #17     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:670:7)
E/flutter ( 6823): #18     _rootRun  (dart:async/zone.dart:1180:38)
E/flutter ( 6823): #19     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 6823): #20     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter ( 6823): #21     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter ( 6823): #22     _rootRun  (dart:async/zone.dart:1184:13)
E/flutter ( 6823): #23     _CustomZone.run  (dart:async/zone.dart:1077:19)
E/flutter ( 6823): #24     _CustomZone.runGuarded  (dart:async/zone.dart:979:7)
E/flutter ( 6823): #25     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1019:23)
E/flutter ( 6823): #26     _microtaskLoop  (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 6823): #27     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:52:5)
E/flutter ( 6823):
```

**Comment by ibrierley** [comment]
Think you may need to show some code for others to get good ideas on the problem.

**Comment by mattia-lau** [comment]
i'm just using the example code, from your repo. I just make this screen as bottom navigation bar item. The first time entry the page is work fine. The second time entry this page will show the error message as i mentioned before.. 


```dart
class NearScreen extends StatefulWidget {
  @override
  NearScreenState createState() => NearScreenState();
}

class NearScreenState extends State<NearScreen> {
  MapController _mapController = MapController();
  List<Marker> _markers = [];
  UserLocationOptions _userLocationOptions;
  MarkerClusterLayerOptions _markerClusterLayerOptions;

  Future<void> _fetchJobs(double lat, double lng) async {
    _mapController.move(LatLng(lat, lng), 13);
    var client = http.Client();
    final response = await client.get(new Uri.https("<api call>", {"lat": lat.toString(), "lng": lng.toString()}));
    if (response.statusCode == 200) {
      List jsonResponse = json.decode(response.body);
      List<Marker> temp = List();
      for (var i = 0; i < jsonResponse.length; i++) {
        ...
        // add marker to temp
      }
      setState(() {
        _markers.addAll(temp);
        _first = true;
      });
    } else {
      print('Failed to load jobs from API');
    }
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  void dispose() {
    super.dispose();
  }

  void onLocationUpdated(LatLng pos) {
    if (!_first) _fetchJobs(pos.latitude, pos.longitude);
  }

  @override
  Widget build(BuildContext context) {
    _userLocationOptions = UserLocationOptions(
        context: context,
        mapController: _mapController,
        markers: _markers,
        onLocationUpdate: onLocationUpdated,
        updateMapLocationOnPositionChange: false,
        showMoveToCurrentLocationFloatingActionButton: true,
        zoomToCurrentLocationOnLoad: false,
        fabBottom: 50,
        fabRight: 50,
        verbose: false);

    _markerClusterLayerOptions = MarkerClusterLayerOptions(
        maxClusterRadius: 120,
        size: Size(40, 40),
        fitBoundsOptions: FitBoundsOptions(
          padding: EdgeInsets.all(50),
        ),
        markers: [..._markers],
        polygonOptions: PolygonOptions(
            borderColor: Colors.blueAccent,
            color: Colors.black12,
            borderStrokeWidth: 3),
        builder: (context, marker) {
          return FloatingActionButton(
            child: Text(marker.length.toString()),
            onPressed: null,
          );
        });

    return Scaffold(
      body: FlutterMap(
        options: MapOptions(
          center: LatLng(27.7172, 85.3240),
          zoom: 13.0,
          plugins: [
            MyCustomPlugin(),
            UserLocationPlugin(),
            MarkerClusterPlugin(),
            DetailsPlugin()
          ],
        ),
        layers: [
          TileLayerOptions(
            urlTemplate: "https://api.tiles.mapbox.com/v4/"
                "{id}/{z}/{x}/{y}@2x.png?access_token={accessToken}",
            additionalOptions: {
              'accessToken':
                  '<access_token>',
              'id': 'mapbox.streets',
            },
          ),
          _markerClusterLayerOptions,
          _userLocationOptions,
          MyCustomPluginOptions(),
          
        ],
        mapController: _mapController,
      ),
    );
  }
}

```

**Comment by mtan11** [comment]
I have the same issue. Any help to fix it please?
