### ISSUE TITLE
many errors .. and suggestions ..

### ISSUE THREAD

**Issue by imeDevelopers** [fleaflet/flutter_map#692]
first open ... the first open air show nothing ... except the markers and polygons ...

```
[ +349 ms] I/flutter ( 2391): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
[  +12 ms] I/flutter ( 2391): The following NoSuchMethodError was thrown building
StreamBuilder<int>(dirty, state:
[  +38 ms] I/flutter ( 2391): _StreamBuilderBaseState<int, AsyncSnapshot<int>>#3cfba):
[  +44 ms] I/flutter ( 2391): The getter 'iterator' was called on null.
[   +4 ms] I/flutter ( 2391): Receiver: null
[   +4 ms] I/flutter ( 2391): Tried calling: iterator
[   +3 ms] I/flutter ( 2391): 
[   +3 ms] I/flutter ( 2391): The relevant error-causing widget was:
[  +99 ms] I/flutter ( 2391):   StreamBuilder<int>
[   +6 ms] I/flutter ( 2391):
file:///E:/Android/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_map-0.9.0/lib/src/layer/marker_layer.dart:110:12
[   +9 ms] I/flutter ( 2391): 
[   +4 ms] I/flutter ( 2391): When the exception was thrown, this was the stack:
[   +4 ms] I/flutter ( 2391): #0      Object.noSuchMethod
(dart:core-patch/object_patch.dart:51:5)
[  +38 ms] I/flutter ( 2391): #1      MarkerLayer.build.<anonymous closure>
(package:flutter_map/src/layer/marker_layer.dart:114:42)
[   +6 ms] I/flutter ( 2391): #2      StreamBuilder.build
(package:flutter/src/widgets/async.dart:514:81)
[   +6 ms] I/flutter ( 2391): #3      _StreamBuilderBaseState.build
(package:flutter/src/widgets/async.dart:129:48)
[   +6 ms] I/flutter ( 2391): #4      StatefulElement.build
(package:flutter/src/widgets/framework.dart:4663:28)
[   +6 ms] I/flutter ( 2391): #5      ComponentElement.performRebuild
(package:flutter/src/widgets/framework.dart:4546:15)
[  +33 ms] I/flutter ( 2391): #6      StatefulElement.performRebuild
(package:flutter/src/widgets/framework.dart:4719:11)
[  +44 ms] I/flutter ( 2391): #7      Element.rebuild
(package:flutter/src/widgets/framework.dart:4262:5)
[   +6 ms] I/flutter ( 2391): #8      ComponentElement._firstBuild
(package:flutter/src/widgets/framework.dart:4525:5)
[   +8 ms] I/flutter ( 2391): #9      StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:4710:11)
[  +69 ms] I/flutter ( 2391): #10     ComponentElement.mount
(package:flutter/src/widgets/framework.dart:4520:5)
[   +6 ms] I/flutter ( 2391): ...     Normal element mounting (7 frames)
[   +6 ms] I/flutter ( 2391): #17     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3490:14)
[   +5 ms] I/flutter ( 2391): #18     MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:5991:32)
[   +6 ms] I/flutter ( 2391): ...     Normal element mounting (35 frames)
[  +34 ms] I/flutter ( 2391): #53     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3490:14)
[   +8 ms] I/flutter ( 2391): #54     Element.updateChild
(package:flutter/src/widgets/framework.dart:3258:18)
[   +6 ms] I/flutter ( 2391): #55     _LayoutBuilderElement._layout.<anonymous closure>
(package:flutter/src/widgets/layout_builder.dart:137:18)
[   +6 ms] I/flutter ( 2391): #56     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2620:19)
[   +9 ms] I/flutter ( 2391): #57     _LayoutBuilderElement._layout
(package:flutter/src/widgets/layout_builder.dart:117:11)
[  +39 ms] I/flutter ( 2391): #58     RenderObject.invokeLayoutCallback.<anonymous closure>
(package:flutter/src/rendering/object.dart:1868:58)
[   +6 ms] I/flutter ( 2391): #59     PipelineOwner._enableMutationsToDirtySubtrees
(package:flutter/src/rendering/object.dart:920:15)
[   +5 ms] I/flutter ( 2391): #60     RenderObject.invokeLayoutCallback
(package:flutter/src/rendering/object.dart:1868:13)
[   +4 ms] I/flutter ( 2391): #61     RenderConstrainedLayoutBuilder.rebuildIfNecessary
(package:flutter/src/widgets/layout_builder.dart:226:7)
[  +44 ms] I/flutter ( 2391): #62     _RenderLayoutBuilder.performLayout
(package:flutter/src/widgets/layout_builder.dart:299:5)
[   +7 ms] I/flutter ( 2391): #63     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +4 ms] I/flutter ( 2391): #64     RenderStack.performLayout
(package:flutter/src/rendering/stack.dart:560:15)
[   +6 ms] I/flutter ( 2391): #65     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +40 ms] I/flutter ( 2391): #66     MultiChildLayoutDelegate.layoutChild
(package:flutter/src/rendering/custom_layout.dart:173:11)
[   +7 ms] I/flutter ( 2391): #67     _ScaffoldLayout.performLayout
(package:flutter/src/material/scaffold.dart:495:7)
[   +6 ms] I/flutter ( 2391): #68     MultiChildLayoutDelegate._callPerformLayout
(package:flutter/src/rendering/custom_layout.dart:242:7)
[   +6 ms] I/flutter ( 2391): #69     RenderCustomMultiChildLayoutBox.performLayout
(package:flutter/src/rendering/custom_layout.dart:401:14)
[  +34 ms] I/flutter ( 2391): #70     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +38 ms] I/flutter ( 2391): #71     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +7 ms] I/flutter ( 2391): #72     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +6 ms] I/flutter ( 2391): #73     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +5 ms] I/flutter ( 2391): #74     _RenderCustomClip.performLayout
(package:flutter/src/rendering/proxy_box.dart:1269:11)
[  +47 ms] I/flutter ( 2391): #75     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +5 ms] I/flutter ( 2391): #76     RenderPadding.performLayout
(package:flutter/src/rendering/shifted_box.dart:209:11)
[   +6 ms] I/flutter ( 2391): #77     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +4 ms] I/flutter ( 2391): #78     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[  +42 ms] I/flutter ( 2391): #79     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +7 ms] I/flutter ( 2391): #80     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +6 ms] I/flutter ( 2391): #81     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +12 ms] I/flutter ( 2391): #82     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[  +40 ms] I/flutter ( 2391): #83     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +8 ms] I/flutter ( 2391): #84     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +5 ms] I/flutter ( 2391): #85     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +38 ms] I/flutter ( 2391): #86     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +8 ms] I/flutter ( 2391): #87     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +5 ms] I/flutter ( 2391): #88     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +6 ms] I/flutter ( 2391): #89     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +4 ms] I/flutter ( 2391): #90     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[  +36 ms] I/flutter ( 2391): #91     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +44 ms] I/flutter ( 2391): #92     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +6 ms] I/flutter ( 2391): #93     RenderOffstage.performLayout
(package:flutter/src/rendering/proxy_box.dart:3228:13)
[   +5 ms] I/flutter ( 2391): #94     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +35 ms] I/flutter ( 2391): #95     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[  +34 ms] I/flutter ( 2391): #96     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +6 ms] I/flutter ( 2391): #97     _RenderTheatre.performLayout
(package:flutter/src/widgets/overlay.dart:702:15)
[   +7 ms] I/flutter ( 2391): #98     RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +7 ms] I/flutter ( 2391): #99     RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +5 ms] I/flutter ( 2391): #100    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +31 ms] I/flutter ( 2391): #101    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[  +38 ms] I/flutter ( 2391): #102    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +6 ms] I/flutter ( 2391): #103    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +7 ms] I/flutter ( 2391): #104    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +6 ms] I/flutter ( 2391): #105    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[  +32 ms] I/flutter ( 2391): #106    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +43 ms] I/flutter ( 2391): #107    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +6 ms] I/flutter ( 2391): #108    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +7 ms] I/flutter ( 2391): #109    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +7 ms] I/flutter ( 2391): #110    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +35 ms] I/flutter ( 2391): #111    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[  +34 ms] I/flutter ( 2391): #112    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +6 ms] I/flutter ( 2391): #113    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +5 ms] I/flutter ( 2391): #114    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +7 ms] I/flutter ( 2391): #115    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +5 ms] I/flutter ( 2391): #116    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +32 ms] I/flutter ( 2391): #117    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[  +37 ms] I/flutter ( 2391): #118    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +5 ms] I/flutter ( 2391): #119    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +5 ms] I/flutter ( 2391): #120    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +6 ms] I/flutter ( 2391): #121    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +5 ms] I/flutter ( 2391): #122    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +37 ms] I/flutter ( 2391): #123    RenderOffstage.performLayout
(package:flutter/src/rendering/proxy_box.dart:3226:14)
[   +6 ms] I/flutter ( 2391): #124    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[   +9 ms] I/flutter ( 2391): #125    RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:115:13)
[   +8 ms] I/flutter ( 2391): #126    RenderObject.layout
(package:flutter/src/rendering/object.dart:1769:7)
[  +31 ms] I/flutter ( 2391): #127    _RenderTheatre.performLayout
(package:flutter/src/widgets/overlay.dart:702:15)
[  +32 ms] I/flutter ( 2391): #128    RenderObject._layoutWithoutResize
(package:flutter/src/rendering/object.dart:1632:7)
[  +38 ms] I/flutter ( 2391): #129    PipelineOwner.flushLayout
(package:flutter/src/rendering/object.dart:889:18)
[   +8 ms] I/flutter ( 2391): #130    RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:404:19)
[   +6 ms] I/flutter ( 2391): #131    WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:867:13)
[   +7 ms] I/flutter ( 2391): #132    RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:286:5)
[  +35 ms] I/flutter ( 2391): #133    SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1115:15)
[  +31 ms] I/flutter ( 2391): #134    SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1054:9)
[   +7 ms] I/flutter ( 2391): #135    SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:970:5)
[  +36 ms] I/flutter ( 2391): #139    _invoke (dart:ui/hooks.dart:253:10)
[   +4 ms] I/flutter ( 2391): #140    _drawFrame (dart:ui/hooks.dart:211:3)
[   +4 ms] I/flutter ( 2391): (elided 3 frames from dart:async)
[   +3 ms] I/flutter ( 2391): 
[  +40 ms] I/flutter ( 2391):
════════════════════════════════════════════════════════════════════════════════════════════════════
[   +9 ms] E/Parcel  ( 2391): Reading a NULL string not supported here.
[   +4 ms] I/BiChannelGoogleApi( 2391): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: 
com.google.firebase.auth.api.internal.zzaq@a962e8b
[   +7 ms] E/Parcel  ( 2391): Reading a NULL string not supported here.
[   +4 ms] I/BiChannelGoogleApi( 2391): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: 
com.google.firebase.auth.api.internal.zzaq@a962e8b
[  +42 ms] E/Parcel  ( 2391): Reading a NULL string not supported here.
[   +4 ms] I/flutter ( 2391): Another exception was thrown: NoSuchMethodError: The getter      
'iterator' was called on null.
[   +8 ms] W/System  ( 2391): A resource failed to call release. 
[   +3 ms] I/chatty  ( 2391): uid=10400(my.app) FinalizerDaemon identical 4 lines  
[  +46 ms] W/System  ( 2391): A resource failed to call release. 
[   +9 ms] I/flutter ( 2391): Another exception was thrown: NoSuchMethodError: The getter
'iterator' was called on null.
[   +6 ms] I/flutter ( 2391): Another exception was thrown: NoSuchMethodError: The getter      
'iterator' was called on null.
[ +462 ms] I/flutter ( 2391): Another exception was thrown: NoSuchMethodError: The getter
'iterator' was called on null.
[ +268 ms] I/flutter ( 2391): Another exception was thrown: NoSuchMethodError: The getter
'iterator' was called on null.
[ +133 ms] I/flutter ( 2391): Another exception was thrown: Couldn't download or retrieve file.[ +210 ms] I/chatty  ( 2391): uid=10400(my.app) 1.ui identical 6 lines
[   +5 ms] I/flutter ( 2391): Another exception was thrown: Couldn't download or retrieve file.[ +459 ms] I/flutter ( 2391): Couldn't download or retrieve file.
[ +198 ms] I/chatty  ( 2391): uid=10400(my.app) 1.ui identical 3 lines
[   +5 ms] I/flutter ( 2391): Couldn't download or retrieve file.
[ +477 ms] I/flutter ( 2391): Couldn't download or retrieve file.
[ +107 ms] I/chatty  ( 2391): uid=10400(my.app) 1.ui identical 1 line
[   +4 ms] I/flutter ( 2391): Couldn't download or retrieve file.
```

when i change maptype eg. ...

'id': 'mapbox.satellite' or 'mapbox.streets' .. it change but the area what i already focus on are stil as it is until i change the complete area to see the changes ..

--------------------------------------------------
i fixed the error above , but now i have new one ..

```
[   +8 ms] E/MethodChannel#flutter/platform_views(16793): Failed to handle method call
[   +3 ms] E/MethodChannel#flutter/platform_views(16793): java.lang.ClassCastException:        
java.lang.Integer cannot be cast to java.util.Map
[   +4 ms] E/MethodChannel#flutter/platform_views(16793):       at
io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.dispose(PlatformViewsChannel.java:113)
[   +8 ms] E/MethodChannel#flutter/platform_views(16793):       at
io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:62)
[  +42 ms] E/MethodChannel#flutter/platform_views(16793):       at
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
[   +8 ms] E/MethodChannel#flutter/platform_views(16793):       at
io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)    
[   +7 ms] E/MethodChannel#flutter/platform_views(16793):       at
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:682)
[   +4 ms] E/MethodChannel#flutter/platform_views(16793):       at
android.os.MessageQueue.nativePollOnce(Native Method)
[  +45 ms] E/MethodChannel#flutter/platform_views(16793):       at
android.os.MessageQueue.next(MessageQueue.java:326)
[   +5 ms] E/MethodChannel#flutter/platform_views(16793):       at
android.os.Looper.loop(Looper.java:189)
[   +6 ms] E/MethodChannel#flutter/platform_views(16793):       at
android.app.ActivityThread.main(ActivityThread.java:7214)
[   +6 ms] E/MethodChannel#flutter/platform_views(16793):       at
java.lang.reflect.Method.invoke(Native Method)
[  +38 ms] E/MethodChannel#flutter/platform_views(16793):       at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
[   +6 ms] E/MethodChannel#flutter/platform_views(16793):       at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:888)
[   +5 ms] E/flutter (16793): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception:PlatformException(error, java.lang.Integer cannot be cast to java.util.Map, null)
[   +6 ms] E/flutter (16793): #0      StandardMethodCodec.decodeEnvelope
(package:flutter/src/services/message_codecs.dart:572:7)
[   +4 ms] E/flutter (16793): #1      MethodChannel._invokeMethod
(package:flutter/src/services/platform_channel.dart:161:18)
[  +36 ms] E/flutter (16793): <asynchronous suspension>
[   +5 ms] E/flutter (16793): #2      MethodChannel.invokeMethod
(package:flutter/src/services/platform_channel.dart:334:12)
[   +6 ms] E/flutter (16793): #3      TextureAndroidViewController._sendDisposeMessage
(package:flutter/src/services/platform_views.dart:1044:42)
[   +5 ms] E/flutter (16793): #4      AndroidViewController.dispose
(package:flutter/src/services/platform_views.dart:893:13)
[   +5 ms] E/flutter (16793): #5      _AndroidViewState.dispose
(package:flutter/src/widgets/platform_view.dart:493:17)
[  +38 ms] E/flutter (16793): #6      StatefulElement.unmount
(package:flutter/src/widgets/framework.dart:4773:12)
[   +5 ms] E/flutter (16793): #7      _InactiveElements._unmount
(package:flutter/src/widgets/framework.dart:1935:13)
[   +7 ms] E/flutter (16793): #8      ListIterable.forEach (dart:_internal/iterable.dart:39:13)[   +4 ms] E/flutter (16793): #9      _InactiveElements._unmountAll
(package:flutter/src/widgets/framework.dart:1944:25)
[   +7 ms] E/flutter (16793): #10     BuildOwner.finalizeTree.<anonymous closure>
(package:flutter/src/widgets/framework.dart:2754:27)
[  +44 ms] E/flutter (16793): #11     BuildOwner.lockState
(package:flutter/src/widgets/framework.dart:2558:15)
[   +6 ms] E/flutter (16793): #12     BuildOwner.finalizeTree
(package:flutter/src/widgets/framework.dart:2753:7)
[   +5 ms] E/flutter (16793): #13     WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:868:18)
[   +5 ms] E/flutter (16793): #14     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:286:5)
[  +57 ms] E/flutter (16793): #15     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1115:15)
[   +5 ms] E/flutter (16793): #16     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1054:9)
[  +43 ms] E/flutter (16793): #17     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:970:5)
[   +6 ms] E/flutter (16793): #18     _rootRun (dart:async/zone.dart:1190:13)
[   +4 ms] E/flutter (16793): #19     _CustomZone.run (dart:async/zone.dart:1093:19)
[   +3 ms] E/flutter (16793): #20     _CustomZone.runGuarded (dart:async/zone.dart:997:7)      
[  +46 ms] E/flutter (16793): #21     _invoke (dart:ui/hooks.dart:253:10)
[   +5 ms] E/flutter (16793): #22     _drawFrame (dart:ui/hooks.dart:211:3)
[   +4 ms] E/flutter (16793):
``` 
--------------------------------------------------
a question:
what is the alternative 'id' for 'mapbox.satellite' and 'mapbox.streets' ?
i want to see 'mapbox.satellite' with street titles and streets lines on this id , what is the right one ?

--------------------------------------------------

another problems ... , in [google_maps_flutter] the markers and polylines have onTap: option .. , why you don't add this option ?

if i used IconButton() as marker i want it to be clickable like google maps ...

and i want to see marker info window like google ..
--------------------------------------------------

look at this comment: https://github.com/flutter/flutter/issues/54557#issuecomment-660338657

**Comment by imeDevelopers** [comment]
we need traffic layer like google maps ..
