### ISSUE TITLE
Error during app start: The method 'replaceAllMapped' was called on null.

### ISSUE THREAD

**Issue by komape** [fleaflet/flutter_map#708]
## Description of the error

During the start of my app, Flutter Map is throwing the following error. In debug mode map view shortly shows an error. But just half a second later the map is displayed correctly. I could ignore that but it makes me feel uncomfortable to know that at every app start flies an exception.

Do you know how to avoid that or fix it?

```log
I/flutter (21974): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21974): The following NoSuchMethodError was thrown building Listener:
I/flutter (21974): The method 'replaceAllMapped' was called on null.
I/flutter (21974): Receiver: null
I/flutter (21974): Tried calling: replaceAllMapped(RegExp: pattern=\{ *([\w_-]+) *\} flags=, Closure: (Match) =>
I/flutter (21974): String)
I/flutter (21974):
I/flutter (21974): The relevant error-causing widget was:
I/flutter (21974):   GestureDetector
I/flutter (21974):   ../…/map/flutter_map_state.dart:118
I/flutter (21974):
I/flutter (21974): When the exception was thrown, this was the stack:
I/flutter (21974): #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:53:5)
I/flutter (21974): #1      template package:flutter_map/…/core/util.dart:11
I/flutter (21974): #2      TileProvider.getTileUrl package:flutter_map/…/tile_provider/tile_provider.dart:38
I/flutter (21974): #3      CachedNetworkTileProvider.getImage package:flutter_map/…/tile_provider/tile_provider.dart:69
I/flutter (21974): #4      _TileLayerState._addTile package:flutter_map/…/layer/tile_layer.dart:946
I/flutter (21974): #5      _TileLayerState._update package:flutter_map/…/layer/tile_layer.dart:893
I/flutter (21974): #6      _TileLayerState._setView package:flutter_map/…/layer/tile_layer.dart:732
I/flutter (21974): #7      _TileLayerState._resetView package:flutter_map/…/layer/tile_layer.dart:702
I/flutter (21974): #8      _TileLayerState.initState package:flutter_map/…/layer/tile_layer.dart:396
I/flutter (21974): #9      StatefulElement._firstBuild package:flutter/…/widgets/framework.dart:4640
I/flutter (21974): #10     ComponentElement.mount package:flutter/…/widgets/framework.dart:4476
I/flutter (21974): #11     Element.inflateWidget package:flutter/…/widgets/framework.dart:3446
I/flutter (21974): #12     MultiChildRenderObjectElement.mount package:flutter/…/widgets/framework.dart:5947
I/flutter (21974): ...     Normal element mounting (41 frames)
```

## Flutter Doctor
```
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.5 at /home/<my username>/tools/flutter
    • Framework revision 8af6b2f038 (5 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/<my username>/tools/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/<my username>/tools/Android/Sdk
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /usr/local/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • sdk gphone x86 64 arm64 • emulator-5554 • android-x64 • Android 11 (API 30) (emulator)

• No issues found!
```

## Flutter Map
```
  flutter_map: ^0.10.1
```

**Comment by komape** [comment]
The error has disappeared. My guess is that my dark/light preferences caused this. The user can select between a dark and a light theme mode in my app. The map takes the matching tile set. It seems like that the asynchronous read of the preferences is not finished at the moment the map loads the tiles. I have a fallback tile url if the preferences are not loaded yet. As soon as the preferences are loaded, the map updates the tiles.
