### ISSUE TITLE
Error: MissingPluginException no method getTemporaryDirectory on channel plugins.flutter.io/path_provider

### ISSUE THREAD

**Issue by 4F2E4A2E** [fleaflet/flutter_map#773]
Hello there and thank you for this amazing project.

If I understand it correctly, path_provider support for web got removed from dart v2
This error occurs now when trying to load the offline mbtiles in the example.

```
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...
Debug service listening on ws://127.0.0.1:64680/TN2LfajDOhA=
Debug service listening on ws://127.0.0.1:64680/TN2LfajDOhA=
Error: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
    at Object.throw_ [as throw] (http://localhost:64494/dart_sdk.js:4339:11)
    at platform_channel.MethodChannel.new._invokeMethod (http://localhost:64494/packages/flutter/src/services/system_channels.dart.lib.js:944:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:64494/dart_sdk.js:37679:33
    at _RootZone.runUnary (http://localhost:64494/dart_sdk.js:37533:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:64494/dart_sdk.js:32507:29)
    at handleValueCallback (http://localhost:64494/dart_sdk.js:33054:49)
    at Function._propagateToListeners (http://localhost:64494/dart_sdk.js:33092:17)
    at _Future.new.[_completeWithValue] (http://localhost:64494/dart_sdk.js:32935:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:64494/dart_sdk.js:32957:35)
    at Object._microtaskLoop (http://localhost:64494/dart_sdk.js:37794:13)
    at _startMicrotaskLoop (http://localhost:64494/dart_sdk.js:37800:13)
    at http://localhost:64494/dart_sdk.js:33309:9
```

```
Flutter 1.23.0-18.1.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 198df796aa (4 weeks ago) • 2020-10-15 12:04:33 -0700
Engine • revision 1d12d82d9c
Tools • Dart 2.11.0 (build 2.11.0-213.1.beta)
```

**Comment by kengu** [comment]
MBTilesProvider was removed from this library in  version `0.11.0`. In Flutter web the file system is not available. I believe this is causing the MissingPluginException error.
