### ISSUE TITLE
Centering map does not work

### ISSUE THREAD

**Issue by PlutoHDDev** [fleaflet/flutter_map#797]
I am using the map in a form in my Flutter app and centering the map does not work. The map just shows a piece of the ocean.  That's because my fallback value (coordinates) is 0, 0. The marker then get's updated to the correct position from value[0] and value[1], but the center isn't updated.
```
new FlutterMap(
            options: new MapOptions(
              // TODO: Center doesn't refresh
              // https://github.com/fleaflet/flutter_map/issues/10
              center: new latlong.LatLng(value[0], value[1]),
              zoom: 13.0,
            ),
            layers: [
              new TileLayerOptions(urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", subdomains: ['a', 'b', 'c']),
              new MarkerLayerOptions(
                markers: [
                  new Marker(
                    width: 20.0,
                    height: 20.0,
                    point: new latlong.LatLng(value[0], value[1]),
                    builder: (ctx) => new Container(
                      child: Icon(
                        Icons.location_on,
                        color: primaryColor,
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
```
I have no idea why `center: new latlong.LatLng(value[0], value[1]),` does not work. Can someone help me with that?

**Comment by ibrierley** [comment]
Try hardcoding values instead of value[0]. value[1], just to prove if those are what you think. Print them out before your FlutterMap build

**Comment by PlutoHDDev** [comment]
I printed out value[0] and value[1], first it outputs 0 and 0 as expected and later my real coordinates, also as expected. But the center isn't updated.

**Comment by moovida** [comment]
@PlutoHDDev it doesn't update in the build, you need to set them in the mapcontroller.

**Comment by Swepilot** [comment]
You have to use MapController to move the map position once it's been built.

**Comment by ibrierley** [comment]
If you are moving it afterwards, I would personally use a mapController and move() method.

**Comment by PlutoHDDev** [comment]
I already found information about the mapController somewhere, but the problem is that the map is used inside a Stateless Widget which then is used inside a Stateful Widget. 

This is how the map (Input Card) is used:
```
forms.InputCard.position(
          text: AppLocalizations.of(context).translate("location.location"),
          autofetch: true,
          fetch: () => locationMCOF.get(),
          onRemove: () {
            widget.trim.position.remove("latitude");
            widget.trim.position.remove("longitude");
          },
          onValue: (value) async {
            widget.trim.position["latitude"] = [value[0]];
            widget.trim.position["longitude"] = [value[1]];
            // Set position metadata
            Placemark place = (await placemarkFromCoordinates(value[0], value[1])).first;
            widget.trim.position["street"] = place.street;
            widget.trim.position["city"] = place.locality;
            widget.trim.position["country"] = place.country;
            widget.trim.position["postalCode"] = place.postalCode;
          },
        ),
```

**Comment by ibrierley** [comment]
I'm not sure that should matter, you should still be able to use a mapController with it. May need to see more code otherwise, as it's not clear from the bit above what the issue is.

**Comment by PlutoHDDev** [comment]
I have already tried using the MapController, but that gives me the following error:
```
       -I/flutter (21892): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (21892): The following NoSuchMethodError was thrown building InputPosition(dirty):
I/flutter (21892): The method 'move' was called on null.
I/flutter (21892): Receiver: null
I/flutter (21892): Tried calling: move(Instance of 'LatLng', 13.0, hasGesture: false)
I/flutter (21892):
I/flutter (21892): The relevant error-causing widget was:
I/flutter (21892):   InputPosition
I/flutter (21892):   file:///C:/Users/FlorianRachmann/OneDrive/Dokumente/Development/GitHub/trimlog/src/flutter_app/lib/shared/ui_forms.dart:665:16
I/flutter (21892):
I/flutter (21892): When the exception was thrown, this was the stack:
I/flutter (21892): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (21892): #1      MapControllerImpl.move (package:flutter_map/src/map/map.dart:28:12)
I/flutter (21892): #2      InputPosition.build (package:Trimlog/shared/ui_forms.dart:955:19)
I/flutter (21892): #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:4701:28)
I/flutter (21892): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter (21892): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (21892): #6      StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
I/flutter (21892): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (21892): #8      RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5647:32)
I/flutter (21892): #9      MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
I/flutter (21892): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
```
(and so on) with this code:

```
@override
  Widget build(BuildContext context) {
    final MapController mapController = new MapController();
    Column widget = Column(children: [
      isDeactivated ? Container() : Text(dynamicText),
      Container(
        height: 200.0,
        // ClipRRect is used, because borderRadius via Container decoration doesn't work
        child: ClipRRect(
          borderRadius: BorderRadius.circular(20),
          child: new FlutterMap(
            mapController: mapController,
            options: new MapOptions(
              // TODO: Center doesn't refresh
              // https://github.com/fleaflet/flutter_map/issues/10
              center: new latlong.LatLng(value[0], value[1]),
              zoom: 13.0,
            ),
            layers: [
              new TileLayerOptions(urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", subdomains: ['a', 'b', 'c']),
              new MarkerLayerOptions(
                markers: [
                  new Marker(
                    width: 20.0,
                    height: 20.0,
                    point: new latlong.LatLng(value[0], value[1]),
                    builder: (ctx) => new Container(
                      child: Icon(
                        Icons.location_on,
                        color: primaryColor,
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      )
    ]);
    mapController.move(new latlong.LatLng(value[0], value[1]), 13.0);
    return widget;
  }
}
```

**Comment by ibrierley** [comment]
You need to create your mapcontroller outside your build method, or you are resetting it each time. There's a good example in the examples folder for the flutter_map repo.

**Comment by PlutoHDDev** [comment]
I also tried that, same error...
```
class InputPosition extends StatefulWidget {
  // Custom Value Type
  // Actually needs to be List<double>, but it throws exeptions when giving a List<dynamic> with doubles
  final List<dynamic> value;

  // Constructor
  InputPosition({
    this.value,
  }) : super();

  @override
  _InputPositionState createState() => _InputPositionState();
}

class _InputPositionState extends State<InputPosition> {
  MapController mapController;

  @override
  void initState() {
    super.initState();
    mapController = new MapController();
  }

  @override
  Widget build(BuildContext context) {
    inspect(mapController);
    Column map = Column(children: [
      false ? Container() : Text(""),
      Container(
        height: 200.0,
        // ClipRRect is used, because borderRadius via Container decoration doesn't work
        child: ClipRRect(
          borderRadius: BorderRadius.circular(20),
          child: new FlutterMap(
            mapController: mapController,
            options: new MapOptions(
              // TODO: Center doesn't refresh
              // https://github.com/fleaflet/flutter_map/issues/10
              center: new latlong.LatLng(widget.value[0], widget.value[1]),
              zoom: 13.0,
            ),
            layers: [
              new TileLayerOptions(urlTemplate: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", subdomains: ['a', 'b', 'c']),
              new MarkerLayerOptions(
                markers: [
                  new Marker(
                    width: 20.0,
                    height: 20.0,
                    point: new latlong.LatLng(widget.value[0], widget.value[1]),
                    builder: (ctx) => new Container(
                      child: Icon(
                        Icons.location_on,
                        color: Colors.black,
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      )
    ]);
    mapController.move(new latlong.LatLng(widget.value[0], widget.value[1]), 13.0);
    return map;
  }
}
```

**Comment by ibrierley** [comment]
I think that would be a similar problem. Your mapController.move() is in the build method which feels wrong. 

So I'm not sure if it's a logic question...do you know the center points before you create the widget, or after some event (like the user location). The mapcontroller probably hasn't finished initalizing when you call it. So the normal process is probably something like you give center your default values, and then when a user receives a location, you then move the map controller.

**Comment by phyyyl** [comment]
Hello, I'm also involved.
Yes we create the map with the default values of 0/0. Then we load the user position via gps and give the value to the map (where then the center won't refresh).

**Comment by ibrierley** [comment]
So as long as you only call move() when you retrieve the position (outside of build), then it should be fine.

**Comment by PlutoHDDev** [comment]
We found a way to get it working (MapController outside of build function), thank you.
